language: java
jdk:
  - oraclejdk8

before_install:
  - mysql -u travis --password="" < src/test/resources/travis.sql

install: true
script:
  - mvn clean install
cache:
  directories:
  - $HOME/.m2

services:
  - mysql

notifications:
    slack: blesson:g9I5uYwPK5XVsfzxHve2u8BX
