language: java
jdk:
  - oraclejdk8

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('qburst') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

before_install:
  - mysql -u root --password="qburst" < src/test/resources/travis.sql

install: true
script:
  - mvn clean install
cache:
  directories:
  - $HOME/.m2

services:
  - mysql
test:
  adapter: mysql2
  database: expensetracker
  username: root
  encoding: utf8

