language: java
jdk:
  - oraclejdk8

install: true
script:
  - mvn clean install
cache:
  directories:
  - $HOME/.m2

services:
  - mysql
test:
  adapter: mysql2
  database: test-expense
  username: travis
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test-expense;'