language: java
jdk:
  - oraclejdk8

before_install:
  - mysql -u travis --password="" < travis.sql

install: true
script:
  - mvn clean install
cache:
  directories:
  - $HOME/.m2

services:
  - mysql
test:
  adapter: mysql2
  database: expensetracker
  username: travis
  encoding: utf8

